// rollup.config.js
export default {
  input: 'dist/index.js',
  output: {
    file: 'src/wc-bundle.js',
    format: 'esm',
    banner: '/* This file is auto-generated by Rollup. Do not edit directly. */'
  }
};